# -*- coding: utf-8 -*-
"""MachineTranslation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSEvlTwN36WBZeeJjabAu9qZqS178EKQ
"""

import warnings
warnings.filterwarnings("ignore")

from transformers import MarianMTModel, MarianTokenizer
import torch
import torch
print(torch.cuda.is_available())

from transformers import MarianMTModel, MarianTokenizer
import torch

model_name = "Helsinki-NLP/opus-mt-fr-en"

tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

device = torch.device("cuda")
model.to(device)

input_text = "Les étudiants utilisent Google Colab pour leurs expériences."

inputs = tokenizer(input_text, return_tensors="pt", padding=True)
inputs = {k: v.to(device) for k, v in inputs.items()}

translated_tokens = model.generate(**inputs)
translated_text = tokenizer.decode(translated_tokens[0], skip_special_tokens=True)

print("Translated Sentence:", translated_text)

!pip install nbconvert

!jupyter nbconvert --clear-output --inplace your_notebook.ipynb

